name: 'Install node_modules'
description: 'Install node_modules'

inputs:
  cache-version:
      description: 'Cache version is used in cache-key. Changing this key will invalidate previous caches.'
      required: true

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      id: cache-npm
      with:
        path: |
          npm/node_modules
        key: ${{ runner.os}}-build-cache-node-module-${{ inputs.cache-version }}-${{ hashFiles('npm/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-cache-node-module-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: install
      if: steps.cache-npm.outputs.cache-hit != 'true'
      shell: bash
      working-directory: npm
      run: |
        npm ci
    # You can speedup this workflow by using cached ~/.npm when exact node_modules is not available.
    # In that case, be careful about the total cache limit (10GB).