name: 'Install node_modules'
description: 'Install node_modules'
inputs:
  directory:
    description: 'where'
    required: true
    default: 'npm'

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      id: cache-npm
      env:
        cache-name: cache-npm
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('npm/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - run: pwd
      shell: bash

    # Because it restores ~/.npm, it always needs `npm ci` to recover ./node-modules.
    # Instead, we can cache `node-modules` directly. See: https://zenn.dev/odan/scraps/81b2738864a908
    - name: npm ci
      shell: bash
      run: |
        cd npm
        npm ci

