name: hello

on:
  push:

jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: install
        run:
          echo "Hello"
  my_second_job:
    name: My second job
    runs-on: ubuntu-latest
