name: npm

on:
  push:
    paths:
      - 'npm/**'
      - '.github/**npm**'

jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: npm

    steps:
      - uses: actions/checkout@v3

      - name: Cache Node packages
        uses: ./.github/compose/cache-npm

  build:
    name: build
    runs-on: ubuntu-latest
    needs: [install]
    defaults:
      run:
        working-directory: npm

    steps:
      - uses: actions/checkout@v3

      - name: Restore node_modules
        uses: ./.github/compose/cache-npm

      - name: Cache build
        uses: actions/cache@v3
        id: cache-next
        with:
        # https://nextjs.org/docs/advanced-features/ci-build-caching#github-actions
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - if: ${{ steps.cache-next.outputs.cache-hit != 'true' }}
        name: Build
        run: npm run build

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: [install]
    defaults:
      run:
        working-directory: npm

    steps:
      - uses: actions/checkout@v3

      - name: Restore node_modules
        uses: ./.github/compose/cache-npm

      - name: Lint
        run: npm run lint
