name: yarn3

on:
  push:
    paths:
      - 'yarn3/**'

      # This will be triggered by any file if the path includes `yarn` string.
      # e.g. `.github/yarn.yaml`, `.github/yarn333/actions.yaml`
      - '.github/**yarn**'
      # Shorthand of 2 path `.github/**/*yarn*` `.github/**/*yarn*/**`.
      # The syntax can be confusing, because this `**` possibly include `/` as its substring.

jobs:
  install:
    name: install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: yarn3

    steps:
      - uses: actions/checkout@v3
      - name: Install
        uses: ./.github/compose/cache-yarn


  build:
    name: build
    runs-on: ubuntu-latest
    needs: [install]
    defaults:
      run:
        working-directory: yarn3

    steps:
      - uses: actions/checkout@v3

      - name: Install
        uses: ./.github/compose/cache-yarn

      - name: Cache build
        uses: actions/cache@v3
        id: cache-next
        with:
        # https://nextjs.org/docs/advanced-features/ci-build-caching#github-actions
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - if: ${{ steps.cache-next.outputs.cache-hit != 'true' }}
        name: Build
        run: |
          yarn
          yarn build

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: [install]
    defaults:
      run:
        working-directory: yarn3

    steps:
      - uses: actions/checkout@v3

      - name: Install
        uses: ./.github/compose/cache-yarn

      - name: Lint
        run: yarn lint
