name: yarn3

on:
  push:
    paths:
      - 'yarn3/**'
      - '.github/**yarn**'
      # This will be triggered by any file if the path includes `yarn` string.
      # e.g. `.github/yarn.yaml`, `.github/yarn333/actions.yaml`
      # Shorthand of 2 path `.github/**/*yarn*` `.github/**/*yarn*/**`.
      # The syntax can be confusing, because this `**` possibly include `/` as its substring.

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: yarn3

    steps:
      - uses: actions/checkout@v3

      - name: Cache build
        uses: actions/cache@v3
        id: cache-next
        with:
        # https://nextjs.org/docs/advanced-features/ci-build-caching#github-actions
          path: |
            yarn3/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('yarn3/yarn.lock') }}-${{ hashFiles('yarn3/**/*.[jt]s', 'yarn3/**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('yarn3/yarn.lock') }}-

      - if: ${{ steps.cache-next.outputs.cache-hit != 'true' }}
        name: Build
        run: |
          yarn && yarn build

  lint:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: yarn3

    steps:
      - uses: actions/checkout@v3

      - name: Lint
        run: yarn && yarn lint
